export PATH=$HOME/.magit:$PATH
export PATH=$HOME/.orgmode:$PATH
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export PATH=/usr/local/sbin:$PATH
export GOPATH=$HOME/go
export GOROOT="/usr/local/opt/go/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
export EDITOR=nvim
alias ma="magit"
alias ml="magitd"
alias k="kubectl"
alias kc="kubectx"
alias kn="kubens"
alias ks="k9s --readonly"
alias vh="nvim ."
alias me="molecule"
