---
- hosts: all
  # gather_facts: no
  vars:
    user_name: nm
    # https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
    user_password: $6$8M1vUqMSoCVL.Vda$u627ljuT5myUYKpcSEmzK5Imyxj6rzqnQYVKg1kgeCvYE3LjSVr8vAbfLRPaeVMdtTUuAglogBpokPShA0rf80
    ansible_pipelining: true
    ansible_python_interpreter: /usr/bin/python3
  become: true
  pre_tasks:
    - import_tasks: tasks.yml
  roles:
    - role: geerlingguy.docker
      tags: docker
      vars:
        docker_install_compose: true
    # - role: fubarhouse.golang
    #   tags: golang
    #   vars:
    #     go_install_clean: true
    #     GOPATH: "/home/{{ user_name }}/go"
    #     golang_shell_profile: "/home/{{ user_name }}/.bashrc"
    #     go_get:
    #       - name: gopls
    #         url: golang.org/x/tools/gopls@latest
    #         modules: true
    #       - name: jsonnet
    #         url: github.com/google/go-jsonnet/cmd/jsonnet
    #       - name: jb
    #         url: github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
  post_tasks:
    - name: add user to docker group
      tags: docker
      user:
        name: "{{ user_name }}"
        groups: docker
        append: true
