---
- hosts: localhost
  connection: local
  vars:
    git_name: nmlc
    git_email: public.nmlc@gmail.com
  vars_prompt:
    - name: home_dir
      private: false
  tasks:
    - name: Configure git email
      git_config:
        name: user.email
        scope: global
        value: "{{ git_email }}"
    - name: Configure git name
      git_config:
        name: user.name
        scope: global
        value: "{{ git_name }}"
    - name: Ensure that the directory exist
      file:
        path: "{{ home_dir }}/.config"
        state: directory
    - name: vim symlink
      file:
        src: "{{ home_dir }}/dots/vim"
        dest: "{{ home_dir }}/.config/nvim"
        state: link
    - name: Instal Tmux plugin manager
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "{{ home_dir }}/.tmux/plugins/tpm"
        update: no
    - name: tmux.conf symlink
      file:
        src: "{{ home_dir }}/dots/tmux.conf"
        dest: "{{ home_dir }}/.tmux.conf"
        state: link
    - name: orgmode symlink
      file:
        src: "{{ home_dir }}/dots/emacs/orgmode"
        dest: "{{ home_dir }}/.orgmode"
        state: link
    - name: base_profile symlink
      file:
        src: "{{ home_dir }}/dots/bash_profile"
        dest: "{{ home_dir }}/.base_profile"
        state: link
    - name: ensure .bash_profile exist
      file: 
        path: "{{ home_dir }}/.bash_profile"
        state: touch
    - name: source base_profile
      lineinfile:
        path: "{{ home_dir }}/.bash_profile"
        state: present
        regexp: "^source ~/.base_profile"
        line: "source ~/.base_profile"
    - name: magit symlink
      file:
        src: "{{ home_dir }}/dots/emacs/magit"
        dest: "{{ home_dir }}/.magit"
        state: link
    - name: karabiner symlink
      file:
        src: "{{ home_dir }}/dots/osx/karabiner"
        dest: "{{ home_dir }}/.config/karabiner"
        state: link
        force: true
